creation_rules:
  - key_groups:
      - age:
          - age1m3ffsvpmthzdekapjvh7eu8dfv8sce80w39v7npck7zyed65z46s4la6dz
          - age1geq2hqhyyj58dt2ctt8mcy5c230n7kpe4tlunfmwxjzhx8gtee8qrzhfm3
          - age13umf4p586fwud2jqe53jx7thxr0ezj224zwwrkan6fhe0cd8zsuqt8qp2c
          - age104d6az72yr2wv2ur7ax8msugaxmhq5d3eftprwe44wy33xg7dv8sd04n2z
          - age1l75e08kp97suhupp6hcqs4dawlm3dfqgevkjx4y54q3w5gjh6v3qm7sepa
          - age1la3jf39atjz5tsvf05djcj63palt62w5ly03pzndecxeektw444q89jkx5
          - age155389m7zda44z28l962g4g8qjrlraf70dxp6vvfq2y7vk6ptg3xq5czrc6
    path_regex: "secrets/secrets\\..+$"
  - key_groups:
      - age:
          - age1m3ffsvpmthzdekapjvh7eu8dfv8sce80w39v7npck7zyed65z46s4la6dz
          - age1geq2hqhyyj58dt2ctt8mcy5c230n7kpe4tlunfmwxjzhx8gtee8qrzhfm3
    path_regex: "secrets/ras\\..+$"
  - key_groups:
      - age:
          - age1m3ffsvpmthzdekapjvh7eu8dfv8sce80w39v7npck7zyed65z46s4la6dz
          - age13umf4p586fwud2jqe53jx7thxr0ezj224zwwrkan6fhe0cd8zsuqt8qp2c
    path_regex: "secrets/chiffon\\..+$"
  - key_groups:
      - age:
          - age1m3ffsvpmthzdekapjvh7eu8dfv8sce80w39v7npck7zyed65z46s4la6dz
          - age104d6az72yr2wv2ur7ax8msugaxmhq5d3eftprwe44wy33xg7dv8sd04n2z
    path_regex: "secrets/salt\\..+$"
  - key_groups:
      - age:
          - age1m3ffsvpmthzdekapjvh7eu8dfv8sce80w39v7npck7zyed65z46s4la6dz
          - age1l75e08kp97suhupp6hcqs4dawlm3dfqgevkjx4y54q3w5gjh6v3qm7sepa
    path_regex: "secrets/milk\\..+$"
  - key_groups:
      - age:
          - age1m3ffsvpmthzdekapjvh7eu8dfv8sce80w39v7npck7zyed65z46s4la6dz
          - age1la3jf39atjz5tsvf05djcj63palt62w5ly03pzndecxeektw444q89jkx5
    path_regex: "secrets/shama\\..+$"
  - key_groups:
      - age:
          - age1m3ffsvpmthzdekapjvh7eu8dfv8sce80w39v7npck7zyed65z46s4la6dz
          - age155389m7zda44z28l962g4g8qjrlraf70dxp6vvfq2y7vk6ptg3xq5czrc6
    path_regex: "secrets/otohime\\..+$"
keys:
  - age1m3ffsvpmthzdekapjvh7eu8dfv8sce80w39v7npck7zyed65z46s4la6dz
  - age1geq2hqhyyj58dt2ctt8mcy5c230n7kpe4tlunfmwxjzhx8gtee8qrzhfm3
  - age13umf4p586fwud2jqe53jx7thxr0ezj224zwwrkan6fhe0cd8zsuqt8qp2c
  - age104d6az72yr2wv2ur7ax8msugaxmhq5d3eftprwe44wy33xg7dv8sd04n2z
  - age1l75e08kp97suhupp6hcqs4dawlm3dfqgevkjx4y54q3w5gjh6v3qm7sepa
  - age1la3jf39atjz5tsvf05djcj63palt62w5ly03pzndecxeektw444q89jkx5
  - age155389m7zda44z28l962g4g8qjrlraf70dxp6vvfq2y7vk6ptg3xq5czrc6
